server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/imoon?serverTimezone=UTC
    username: root
    password: root123456
    driver: com.mysql.cj.jdbc.Driver

jackson:
  default-property-inclusion: non_null

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: plus.xiexie.biz.pojo,plus.xiexie.biz.vo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl